/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ShellAlimentacaoIndexRouteImport } from './routes/_shell.alimentacao.index'
import { Route as ShellAlimentacaoHistoricoRouteImport } from './routes/_shell.alimentacao.historico'
import { Route as ShellAlimentacaoNovoRouteImport } from './routes/_shell.alimentacao.novo'
import { Route as ShellMonitorIndexRouteImport } from './routes/_shell.monitor.index'
import { Route as ShellMonitorCetonasRouteImport } from './routes/_shell.monitor.cetonas'
import { Route as ShellMonitorGlicemiaRouteImport } from './routes/_shell.monitor.glicemia'
import { Route as ShellMonitorInsulinaIndexRouteImport } from './routes/_shell.monitor.insulina.index'
import { Route as ShellMonitorInsulinaNovaRouteImport } from './routes/_shell.monitor.insulina.nova'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAlimentacaoIndexRoute = ShellAlimentacaoIndexRouteImport.update({
  id: '/alimentacao/',
  path: '/alimentacao/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAlimentacaoHistoricoRoute =
  ShellAlimentacaoHistoricoRouteImport.update({
    id: '/alimentacao/historico',
    path: '/alimentacao/historico',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellAlimentacaoNovoRoute = ShellAlimentacaoNovoRouteImport.update({
  id: '/alimentacao/novo',
  path: '/alimentacao/novo',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMonitorIndexRoute = ShellMonitorIndexRouteImport.update({
  id: '/monitor/',
  path: '/monitor/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMonitorCetonasRoute = ShellMonitorCetonasRouteImport.update({
  id: '/monitor/cetonas',
  path: '/monitor/cetonas',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMonitorGlicemiaRoute = ShellMonitorGlicemiaRouteImport.update({
  id: '/monitor/glicemia',
  path: '/monitor/glicemia',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMonitorInsulinaIndexRoute =
  ShellMonitorInsulinaIndexRouteImport.update({
    id: '/monitor/insulina/',
    path: '/monitor/insulina/',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellMonitorInsulinaNovaRoute =
  ShellMonitorInsulinaNovaRouteImport.update({
    id: '/monitor/insulina/nova',
    path: '/monitor/insulina/nova',
    getParentRoute: () => ShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alimentacao/historico': typeof ShellAlimentacaoHistoricoRoute
  '/alimentacao/novo': typeof ShellAlimentacaoNovoRoute
  '/monitor/cetonas': typeof ShellMonitorCetonasRoute
  '/monitor/glicemia': typeof ShellMonitorGlicemiaRoute
  '/alimentacao/': typeof ShellAlimentacaoIndexRoute
  '/monitor/': typeof ShellMonitorIndexRoute
  '/monitor/insulina/nova': typeof ShellMonitorInsulinaNovaRoute
  '/monitor/insulina/': typeof ShellMonitorInsulinaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alimentacao/historico': typeof ShellAlimentacaoHistoricoRoute
  '/alimentacao/novo': typeof ShellAlimentacaoNovoRoute
  '/monitor/cetonas': typeof ShellMonitorCetonasRoute
  '/monitor/glicemia': typeof ShellMonitorGlicemiaRoute
  '/alimentacao': typeof ShellAlimentacaoIndexRoute
  '/monitor': typeof ShellMonitorIndexRoute
  '/monitor/insulina/nova': typeof ShellMonitorInsulinaNovaRoute
  '/monitor/insulina': typeof ShellMonitorInsulinaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/auth': typeof AuthRoute
  '/_shell/alimentacao/historico': typeof ShellAlimentacaoHistoricoRoute
  '/_shell/alimentacao/novo': typeof ShellAlimentacaoNovoRoute
  '/_shell/monitor/cetonas': typeof ShellMonitorCetonasRoute
  '/_shell/monitor/glicemia': typeof ShellMonitorGlicemiaRoute
  '/_shell/alimentacao/': typeof ShellAlimentacaoIndexRoute
  '/_shell/monitor/': typeof ShellMonitorIndexRoute
  '/_shell/monitor/insulina/nova': typeof ShellMonitorInsulinaNovaRoute
  '/_shell/monitor/insulina/': typeof ShellMonitorInsulinaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/alimentacao/historico'
    | '/alimentacao/novo'
    | '/monitor/cetonas'
    | '/monitor/glicemia'
    | '/alimentacao/'
    | '/monitor/'
    | '/monitor/insulina/nova'
    | '/monitor/insulina/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/alimentacao/historico'
    | '/alimentacao/novo'
    | '/monitor/cetonas'
    | '/monitor/glicemia'
    | '/alimentacao'
    | '/monitor'
    | '/monitor/insulina/nova'
    | '/monitor/insulina'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/auth'
    | '/_shell/alimentacao/historico'
    | '/_shell/alimentacao/novo'
    | '/_shell/monitor/cetonas'
    | '/_shell/monitor/glicemia'
    | '/_shell/alimentacao/'
    | '/_shell/monitor/'
    | '/_shell/monitor/insulina/nova'
    | '/_shell/monitor/insulina/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/alimentacao/': {
      id: '/_shell/alimentacao/'
      path: '/alimentacao'
      fullPath: '/alimentacao/'
      preLoaderRoute: typeof ShellAlimentacaoIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/alimentacao/historico': {
      id: '/_shell/alimentacao/historico'
      path: '/alimentacao/historico'
      fullPath: '/alimentacao/historico'
      preLoaderRoute: typeof ShellAlimentacaoHistoricoRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/alimentacao/novo': {
      id: '/_shell/alimentacao/novo'
      path: '/alimentacao/novo'
      fullPath: '/alimentacao/novo'
      preLoaderRoute: typeof ShellAlimentacaoNovoRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/monitor/': {
      id: '/_shell/monitor/'
      path: '/monitor'
      fullPath: '/monitor/'
      preLoaderRoute: typeof ShellMonitorIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/monitor/cetonas': {
      id: '/_shell/monitor/cetonas'
      path: '/monitor/cetonas'
      fullPath: '/monitor/cetonas'
      preLoaderRoute: typeof ShellMonitorCetonasRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/monitor/glicemia': {
      id: '/_shell/monitor/glicemia'
      path: '/monitor/glicemia'
      fullPath: '/monitor/glicemia'
      preLoaderRoute: typeof ShellMonitorGlicemiaRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/monitor/insulina/': {
      id: '/_shell/monitor/insulina/'
      path: '/monitor/insulina'
      fullPath: '/monitor/insulina/'
      preLoaderRoute: typeof ShellMonitorInsulinaIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/monitor/insulina/nova': {
      id: '/_shell/monitor/insulina/nova'
      path: '/monitor/insulina/nova'
      fullPath: '/monitor/insulina/nova'
      preLoaderRoute: typeof ShellMonitorInsulinaNovaRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAlimentacaoHistoricoRoute: typeof ShellAlimentacaoHistoricoRoute
  ShellAlimentacaoNovoRoute: typeof ShellAlimentacaoNovoRoute
  ShellMonitorCetonasRoute: typeof ShellMonitorCetonasRoute
  ShellMonitorGlicemiaRoute: typeof ShellMonitorGlicemiaRoute
  ShellAlimentacaoIndexRoute: typeof ShellAlimentacaoIndexRoute
  ShellMonitorIndexRoute: typeof ShellMonitorIndexRoute
  ShellMonitorInsulinaNovaRoute: typeof ShellMonitorInsulinaNovaRoute
  ShellMonitorInsulinaIndexRoute: typeof ShellMonitorInsulinaIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAlimentacaoHistoricoRoute: ShellAlimentacaoHistoricoRoute,
  ShellAlimentacaoNovoRoute: ShellAlimentacaoNovoRoute,
  ShellMonitorCetonasRoute: ShellMonitorCetonasRoute,
  ShellMonitorGlicemiaRoute: ShellMonitorGlicemiaRoute,
  ShellAlimentacaoIndexRoute: ShellAlimentacaoIndexRoute,
  ShellMonitorIndexRoute: ShellMonitorIndexRoute,
  ShellMonitorInsulinaNovaRoute: ShellMonitorInsulinaNovaRoute,
  ShellMonitorInsulinaIndexRoute: ShellMonitorInsulinaIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
